services:
  sanctions_db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: sg_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: sanctions_guard_dev
    ports:
      - '5435:5432'
    volumes:
      - sg_dev_data:/var/lib/postgresql/data

  sanctions_db_test:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: sg_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: sanctions_guard_test
    ports:
      - '5436:5432'
    volumes:
      - sg_test_data:/var/lib/postgresql/data
volumes:
  sg_dev_data:
  sg_test_data: